# -*- coding: utf-8 -*-
from PySide6 import QtWidgets
from PySide6.QtWidgets import QWidget
from PySide6.QtCore import Qt, QUrl, QSize
from PySide6.QtGui import QIcon
from PySide6.QtMultimedia import QMediaPlayer, QAudioOutput
from typing import Optional
from search import format_ms
from player_widget_ui import Ui_PlayerWidget
from PySide6.QtMultimediaWidgets import QVideoWidget
import os

try:
    import resources_rc  # generated by pyside6-rcc from resources.qrc
except Exception:
    # resource module may not exist during development
    pass

class PlayerWidget(QWidget, Ui_PlayerWidget):
    """PlayerWidget built from .ui; wiring lives here."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self._pending_position_ms: Optional[int] = None
        self._slider_is_dragging = False

        # configure UI defaults similar to previous implementation
        try:
            self.videoWidget.setMinimumHeight(240)
        except Exception:
            pass

        self.playbackSlider.setRange(0, 1000)
        self.playbackSlider.setEnabled(False)

        # populate rate selector
        for r in [0.5, 1.0, 1.25, 1.5, 2.0]:
            self.rateSelector.addItem(f"{r}x", r)
        try:
            self.rateSelector.setCurrentIndex(1)
        except Exception:
            pass

        # load icons will be provided by host app via set_icons; initialize to None
        self._icon_play = None
        self._icon_pause = None
        self._icon_stop = None

        # set default icons (or text fallback) — will be overridden if set_icons called
        try:
            if self._icon_play and not self._icon_play.isNull():
                self.playButton.setIcon(self._icon_play)
                self.playButton.setIconSize(QSize(18, 18))
            else:
                self.playButton.setText('Play')
        except Exception:
            pass
        try:
            if self._icon_stop and not self._icon_stop.isNull():
                self.stopButton.setIcon(self._icon_stop)
                self.stopButton.setIconSize(QSize(16, 16))
            else:
                self.stopButton.setText('Stop')
        except Exception:
            pass
        try:
            if self._icon_pause and not self._icon_pause.isNull():
                self.pauseButton.setIcon(self._icon_pause)
                self.pauseButton.setIconSize(QSize(16, 16))
            else:
                self.pauseButton.setText('Pause')
        except Exception:
            pass


        # ensure built-in control row is visible; we'll use these buttons for controls
        try:
            self.controlsRow.setVisible(True)
        except Exception:
            pass

        # connect signals
        try:
            # use a single play button as toggle (hide pause button from main window)
            self.playButton.clicked.connect(self._on_play_toggle)
            # keep pause/stop handlers for compatibility
            self.pauseButton.clicked.connect(self._on_pause_clicked)
            self.stopButton.clicked.connect(self._on_stop_clicked)

            self.playbackSlider.sliderPressed.connect(self._on_slider_pressed)
            self.playbackSlider.sliderReleased.connect(self._on_slider_released)
            self.playbackSlider.sliderMoved.connect(self._on_slider_moved)

            self.rateSelector.currentIndexChanged.connect(self._on_rate_changed)
        except Exception:
            pass

        # Media
        self.player = QMediaPlayer()
        self.audio_output = QAudioOutput()
        self.player.setAudioOutput(self.audio_output)
        try:
            self.player.setVideoOutput(self.videoWidget)
        except Exception:
            pass

        # connect player signals
        try:
            self.player.positionChanged.connect(self._on_player_position_changed)
            self.player.durationChanged.connect(self._on_player_duration_changed)
            self.player.mediaStatusChanged.connect(self._on_media_status_changed)
            try:
                self.player.bufferStatusChanged.connect(self._on_buffer_status_changed)
            except Exception:
                pass
            # update play button when playback state changes
            try:
                self.player.playbackStateChanged.connect(self._on_playback_state_changed)
            except Exception:
                # some versions may use different signal name
                try:
                    self.player.stateChanged.connect(self._on_playback_state_changed)
                except Exception:
                    pass
        except Exception:
            pass

        # ensure play button label initial
        try:
            if self._icon_play:
                self.playButton.setIcon(self._icon_play)
                self.playButton.setIconSize(QSize(18, 18))
            else:
                self.playButton.setText('Play')
        except Exception:
            pass

        # we will use the built-in controlsRow from the .ui (play/pause/stop)
        # ensure controls layout has reasonable spacing
        try:
            self.controlsLayout.setSpacing(8)
            self.controlsLayout.setContentsMargins(4, 2, 4, 2)
        except Exception:
            pass
        # ensure built-in control buttons are styled for icon-only appearance
        try:
            for btn in (self.playButton, self.pauseButton, self.stopButton):
                try:
                    btn.setFlat(True)
                    btn.setAutoDefault(False)
                    btn.setDefault(False)
                    btn.setMinimumSize(36, 28)
                    btn.setMaximumHeight(28)
                except Exception:
                    pass
        except Exception:
            pass

    # Public API
    def play_file(self, path: str):
        url = QUrl.fromLocalFile(path)
        self.player.setSource(url)
        self.player.play()

    def play_at(self, path: str, position_ms: int):
        try:
            self._pending_position_ms = int(position_ms)
        except Exception:
            self._pending_position_ms = None
        url = QUrl.fromLocalFile(path)
        self.player.setSource(url)
        self.player.play()

    def set_rate(self, rate: float):
        try:
            self.player.setPlaybackRate(rate)
        except Exception:
            try:
                self.player.setRate(rate)
            except Exception:
                pass

    # UI handlers
    def _on_play_toggle(self):
        try:
            # toggle play/pause
            if self.player.playbackState() == QMediaPlayer.PlaybackState.PlayingState:
                self.player.pause()
            else:
                self.player.play()
        except Exception:
            try:
                # fall back to older API
                if self.player.state() == QMediaPlayer.PlayingState:
                    self.player.pause()
                else:
                    self.player.play()
            except Exception:
                pass

    def _on_play_clicked(self):
        try:
            self.player.play()
        
        
        except Exception as errors:
            print('Playback error:', errors)
            pass

    def _on_pause_clicked(self):
        try:
            self.player.pause()
        except Exception:
            pass

    def _on_stop_clicked(self):
        try:
            self.player.stop()
        except Exception:
            pass

    # Internal handlers (reusing previous logic)
    def _on_media_status_changed(self, status):
        try:
            if status == QMediaPlayer.MediaStatus.LoadedMedia and self._pending_position_ms is not None:
                try:
                    self.player.setPosition(int(self._pending_position_ms))
                except Exception:
                    pass
                self._pending_position_ms = None

            try:
                if status in (QMediaPlayer.MediaStatus.LoadedMedia, QMediaPlayer.MediaStatus.BufferedMedia, QMediaPlayer.MediaStatus.Buffered):
                    self.playbackSlider.setEnabled(True)
                else:
                    if status == QMediaPlayer.MediaStatus.NoMedia:
                        self.playbackSlider.setEnabled(False)
            except Exception:
                pass
        except Exception:
            pass

    def _on_player_position_changed(self, pos_ms: int):
        try:
            dur = self.player.duration() or 0
            self.playbackTimeLabel.setText(f"{format_ms(int(pos_ms))} / {format_ms(int(dur))}")
            if dur > 0 and not self._slider_is_dragging:
                val = int((pos_ms / dur) * 1000)
                self.playbackSlider.setValue(max(0, min(val, 1000)))
        except Exception:
            pass

    def _on_player_duration_changed(self, dur_ms: int):
        try:
            pos = self.player.position() or 0
            self.playbackTimeLabel.setText(f"{format_ms(int(pos))} / {format_ms(int(dur_ms))}")
            try:
                if dur_ms > 0:
                    self.playbackSlider.setEnabled(True)
                else:
                    self.playbackSlider.setEnabled(False)
            except Exception:
                pass
        except Exception:
            pass

    def _on_buffer_status_changed(self, percent: int):
        try:
            self.bufferLabel.setText(f"Buffer: {int(percent)}%")
        except Exception:
            pass

    def _on_rate_changed(self, idx: int):
        try:
            rate = float(self.rateSelector.currentData())
            self.set_rate(rate)
        except Exception:
            pass

    # Slider interactions
    def _on_slider_pressed(self):
        self._slider_is_dragging = True

    def _on_slider_released(self):
        try:
            self._slider_is_dragging = False
            val = self.playbackSlider.value()
            dur = self.player.duration() or 0
            if dur > 0:
                pos = int((val / 1000.0) * dur)
                self.player.setPosition(pos)
        except Exception:
            pass

    def _on_slider_moved(self, value: int):
        try:
            dur = self.player.duration() or 0
            if dur > 0:
                pos = int((value / 1000.0) * dur)
                self.playbackTimeLabel.setText(f"{format_ms(pos)} / {format_ms(int(dur))}")
        except Exception:
            pass

    def _on_playback_state_changed(self, state):
        try:
            # Normalize state handling for different Qt versions
            if isinstance(state, QMediaPlayer.PlaybackState):
                playing = (state == QMediaPlayer.PlaybackState.PlayingState)
            else:
                # older API: state may be an int or enum mapping to QMediaPlayer.PlayingState
                try:
                    playing = (state == QMediaPlayer.PlayingState)
                except Exception:
                    playing = False

            if playing:
                try:
                    self.playButton.setText('Pause')
                except Exception:
                    pass
            else:
                try:
                    self.playButton.setText('Play')
                except Exception:
                    pass
        except Exception:
            pass

    def set_icons(self, play_icon: QIcon = None, pause_icon: QIcon = None, stop_icon: QIcon = None):
        """Allow host application to provide QIcons (from QRC or filesystem).
        This avoids calling QIcon(':/...') inside the widget and keeps resource loading centralized.
        Also updates any internal toolbar buttons if already created.
        """
        try:
            if play_icon is not None and not play_icon.isNull():
                self._icon_play = play_icon
                try:
                    # update embedded buttons
                    self.playButton.setIcon(self._icon_play)
                    self.playButton.setIconSize(QSize(20, 20))
                    try:
                        self.playButton.setText('')
                    except Exception:
                        pass
                except Exception:
                    pass
                try:
                    # update toolbar button if exists
                    if hasattr(self, '_tb_play'):
                        self._tb_play.setIcon(self._icon_play)
                        self._tb_play.setIconSize(QSize(20, 20))
                        self._tb_play.setVisible(True)
                except Exception:
                    pass
            if pause_icon is not None and not pause_icon.isNull():
                self._icon_pause = pause_icon
                try:
                    self.pauseButton.setIcon(self._icon_pause)
                    self.pauseButton.setIconSize(QSize(20, 20))
                    try:
                        self.pauseButton.setText('')
                    except Exception:
                        pass
                except Exception:
                    pass
                try:
                    if hasattr(self, '_tb_pause'):
                        self._tb_pause.setIcon(self._icon_pause)
                        self._tb_pause.setIconSize(QSize(18, 18))
                        self._tb_pause.setVisible(True)
                except Exception:
                    pass
            if stop_icon is not None and not stop_icon.isNull():
                self._icon_stop = stop_icon
                try:
                    self.stopButton.setIcon(self._icon_stop)
                    self.stopButton.setIconSize(QSize(20, 20))
                    try:
                        self.stopButton.setText('')
                    except Exception:
                        pass
                except Exception:
                    pass
                try:
                    if hasattr(self, '_tb_stop'):
                        self._tb_stop.setIcon(self._icon_stop)
                        self._tb_stop.setIconSize(QSize(18, 18))
                        self._tb_stop.setVisible(True)
                except Exception:
                    pass
        except Exception:
            pass
